// copied from /usr/include/x86_64-linux-gnu/asm/unistd_64.h
// renamed from __NR_xx to SYSCALL_xx

#define SYSCALL_read 0
#define SYSCALL_write 1
#define SYSCALL_open 2
#define SYSCALL_close 3
#define SYSCALL_stat 4
#define SYSCALL_fstat 5
#define SYSCALL_lstat 6
#define SYSCALL_poll 7
#define SYSCALL_lseek 8
#define SYSCALL_mmap 9
#define SYSCALL_mprotect 10
#define SYSCALL_munmap 11
#define SYSCALL_brk 12
#define SYSCALL_rt_sigaction 13
#define SYSCALL_rt_sigprocmask 14
#define SYSCALL_rt_sigreturn 15
#define SYSCALL_ioctl 16
#define SYSCALL_pread64 17
#define SYSCALL_pwrite64 18
#define SYSCALL_readv 19
#define SYSCALL_writev 20
#define SYSCALL_access 21
#define SYSCALL_pipe 22
#define SYSCALL_select 23
#define SYSCALL_sched_yield 24
#define SYSCALL_mremap 25
#define SYSCALL_msync 26
#define SYSCALL_mincore 27
#define SYSCALL_madvise 28
#define SYSCALL_shmget 29
#define SYSCALL_shmat 30
#define SYSCALL_shmctl 31
#define SYSCALL_dup 32
#define SYSCALL_dup2 33
#define SYSCALL_pause 34
#define SYSCALL_nanosleep 35
#define SYSCALL_getitimer 36
#define SYSCALL_alarm 37
#define SYSCALL_setitimer 38
#define SYSCALL_getpid 39
#define SYSCALL_sendfile 40
#define SYSCALL_socket 41
#define SYSCALL_connect 42
#define SYSCALL_accept 43
#define SYSCALL_sendto 44
#define SYSCALL_recvfrom 45
#define SYSCALL_sendmsg 46
#define SYSCALL_recvmsg 47
#define SYSCALL_shutdown 48
#define SYSCALL_bind 49
#define SYSCALL_listen 50
#define SYSCALL_getsockname 51
#define SYSCALL_getpeername 52
#define SYSCALL_socketpair 53
#define SYSCALL_setsockopt 54
#define SYSCALL_getsockopt 55
#define SYSCALL_clone 56
#define SYSCALL_fork 57
#define SYSCALL_vfork 58
#define SYSCALL_execve 59
#define SYSCALL_exit 60
#define SYSCALL_wait4 61
#define SYSCALL_kill 62
#define SYSCALL_uname 63
#define SYSCALL_semget 64
#define SYSCALL_semop 65
#define SYSCALL_semctl 66
#define SYSCALL_shmdt 67
#define SYSCALL_msgget 68
#define SYSCALL_msgsnd 69
#define SYSCALL_msgrcv 70
#define SYSCALL_msgctl 71
#define SYSCALL_fcntl 72
#define SYSCALL_flock 73
#define SYSCALL_fsync 74
#define SYSCALL_fdatasync 75
#define SYSCALL_truncate 76
#define SYSCALL_ftruncate 77
#define SYSCALL_getdents 78
#define SYSCALL_getcwd 79
#define SYSCALL_chdir 80
#define SYSCALL_fchdir 81
#define SYSCALL_rename 82
#define SYSCALL_mkdir 83
#define SYSCALL_rmdir 84
#define SYSCALL_creat 85
#define SYSCALL_link 86
#define SYSCALL_unlink 87
#define SYSCALL_symlink 88
#define SYSCALL_readlink 89
#define SYSCALL_chmod 90
#define SYSCALL_fchmod 91
#define SYSCALL_chown 92
#define SYSCALL_fchown 93
#define SYSCALL_lchown 94
#define SYSCALL_umask 95
#define SYSCALL_gettimeofday 96
#define SYSCALL_getrlimit 97
#define SYSCALL_getrusage 98
#define SYSCALL_sysinfo 99
#define SYSCALL_times 100
#define SYSCALL_ptrace 101
#define SYSCALL_getuid 102
#define SYSCALL_syslog 103
#define SYSCALL_getgid 104
#define SYSCALL_setuid 105
#define SYSCALL_setgid 106
#define SYSCALL_geteuid 107
#define SYSCALL_getegid 108
#define SYSCALL_setpgid 109
#define SYSCALL_getppid 110
#define SYSCALL_getpgrp 111
#define SYSCALL_setsid 112
#define SYSCALL_setreuid 113
#define SYSCALL_setregid 114
#define SYSCALL_getgroups 115
#define SYSCALL_setgroups 116
#define SYSCALL_setresuid 117
#define SYSCALL_getresuid 118
#define SYSCALL_setresgid 119
#define SYSCALL_getresgid 120
#define SYSCALL_getpgid 121
#define SYSCALL_setfsuid 122
#define SYSCALL_setfsgid 123
#define SYSCALL_getsid 124
#define SYSCALL_capget 125
#define SYSCALL_capset 126
#define SYSCALL_rt_sigpending 127
#define SYSCALL_rt_sigtimedwait 128
#define SYSCALL_rt_sigqueueinfo 129
#define SYSCALL_rt_sigsuspend 130
#define SYSCALL_sigaltstack 131
#define SYSCALL_utime 132
#define SYSCALL_mknod 133
#define SYSCALL_uselib 134
#define SYSCALL_personality 135
#define SYSCALL_ustat 136
#define SYSCALL_statfs 137
#define SYSCALL_fstatfs 138
#define SYSCALL_sysfs 139
#define SYSCALL_getpriority 140
#define SYSCALL_setpriority 141
#define SYSCALL_sched_setparam 142
#define SYSCALL_sched_getparam 143
#define SYSCALL_sched_setscheduler 144
#define SYSCALL_sched_getscheduler 145
#define SYSCALL_sched_get_priority_max 146
#define SYSCALL_sched_get_priority_min 147
#define SYSCALL_sched_rr_get_interval 148
#define SYSCALL_mlock 149
#define SYSCALL_munlock 150
#define SYSCALL_mlockall 151
#define SYSCALL_munlockall 152
#define SYSCALL_vhangup 153
#define SYSCALL_modify_ldt 154
#define SYSCALL_pivot_root 155
#define SYSCALL__sysctl 156
#define SYSCALL_prctl 157
#define SYSCALL_arch_prctl 158
#define SYSCALL_adjtimex 159
#define SYSCALL_setrlimit 160
#define SYSCALL_chroot 161
#define SYSCALL_sync 162
#define SYSCALL_acct 163
#define SYSCALL_settimeofday 164
#define SYSCALL_mount 165
#define SYSCALL_umount2 166
#define SYSCALL_swapon 167
#define SYSCALL_swapoff 168
#define SYSCALL_reboot 169
#define SYSCALL_sethostname 170
#define SYSCALL_setdomainname 171
#define SYSCALL_iopl 172
#define SYSCALL_ioperm 173
#define SYSCALL_create_module 174
#define SYSCALL_init_module 175
#define SYSCALL_delete_module 176
#define SYSCALL_get_kernel_syms 177
#define SYSCALL_query_module 178
#define SYSCALL_quotactl 179
#define SYSCALL_nfsservctl 180
#define SYSCALL_getpmsg 181
#define SYSCALL_putpmsg 182
#define SYSCALL_afs_syscall 183
#define SYSCALL_tuxcall 184
